export * from './src/isAlpha';
export * from './src/isArray';
export * from './src/isBlank';
export * from './src/isBoolean';
export * from './src/isDecimal';
export * from './src/isDef';
export * from './src/isEmptyArray';
export * from './src/isEmptyObject';
export * from './src/isError';
export * from './src/isTrue'
export * from './src/isFalse';
export * from './src/isFunction';
export * from './src/isHtmlElement';
export * from './src/isIdentityCodeValid';
export * from './src/isNegativeDecimal';
export * from './src/isNull';
export * from './src/isNumber';
export * from './src/isObject';
export * from './src/isPlainObject';
export * from './src/isPositiveDecimal';
export * from './src/isPrmitive';
export * from './src/isString';
export * from './src/isSymbol';
export * from './'
export * from './src/isUndefined';
